//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KittyAltruistic.CPlusPlusTestRunner {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KittyAltruistic.CPlusPlusTestRunner.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create tool window..
        /// </summary>
        internal static string CanNotCreateWindow {
            get {
                return ResourceManager.GetString("CanNotCreateWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured when trying to execute the tester command line:.
        /// </summary>
        internal static string CommandLineErrorMessage {
            get {
                return ResourceManager.GetString("CommandLineErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Tests.
        /// </summary>
        internal static string ctxTestListMenu_Run {
            get {
                return ResourceManager.GetString("ctxTestListMenu_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --gtest_list_tests.
        /// </summary>
        internal static string DefaultGTestList {
            get {
                return ResourceManager.GetString("DefaultGTestList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --gtest_output=&quot;xml:$outputFile$&quot; --gtest_filter=&quot;$tests$&quot;.
        /// </summary>
        internal static string DefaultGTestRun {
            get {
                return ResourceManager.GetString("DefaultGTestRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string FilterByAllTestsText {
            get {
                return ResourceManager.GetString("FilterByAllTestsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invaild File Chosen.
        /// </summary>
        internal static string GSettings_cmdSet_Click_Invaild_File_Chosen {
            get {
                return ResourceManager.GetString("GSettings_cmdSet_Click_Invaild_File_Chosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restore the defaults?.
        /// </summary>
        internal static string GSettings_DefaultsChanged_Text {
            get {
                return ResourceManager.GetString("GSettings_DefaultsChanged_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm?.
        /// </summary>
        internal static string GSettings_DefaultsChanged_Title {
            get {
                return ResourceManager.GetString("GSettings_DefaultsChanged_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program contains tests written using Google Test. You can use the.
        /// </summary>
        internal static string GTestHelpString {
            get {
                return ResourceManager.GetString("GTestHelpString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Test.
        /// </summary>
        internal static string MarkerDebug {
            get {
                return ResourceManager.GetString("MarkerDebug", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MarkerImage {
            get {
                object obj = ResourceManager.GetObject("MarkerImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Test.
        /// </summary>
        internal static string MarkerRun {
            get {
                return ResourceManager.GetString("MarkerRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Executable set to run tests from.
        /// </summary>
        internal static string NoExeToRunFrom {
            get {
                return ResourceManager.GetString("NoExeToRunFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tests to run.
        /// </summary>
        internal static string NoTests {
            get {
                return ResourceManager.GetString("NoTests", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap TestFail {
            get {
                object obj = ResourceManager.GetObject("TestFail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TestNotRun {
            get {
                object obj = ResourceManager.GetObject("TestNotRun", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TestPassed {
            get {
                object obj = ResourceManager.GetObject("TestPassed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tests are in progress plz wait.
        /// </summary>
        internal static string TestsInProgress {
            get {
                return ResourceManager.GetString("TestsInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test List.
        /// </summary>
        internal static string ToolWindowTitle {
            get {
                return ResourceManager.GetString("ToolWindowTitle", resourceCulture);
            }
        }
    }
}
